## Project 
139 data set

In [2]:
import pandas as pd
import matplotlib
import numpy as np
import seaborn as sns
import statsmodels.api as sm
import statsmodels.stats.api as sms
import scipy.stats as stats
from sklearn import preprocessing

In [3]:
filename_1 = "data/gateways.csv"
filename_2 = "data/readings.csv"
filename_3 = "data/units.csv"

In [ ]:
data_1 = pd.read_csv(filename_1, 
                   sep=';', index_col=13)
data_1.head(20)
#data_1.iloc[1999:2020] # id_unit from 2000 to end are NaN

,seen_last,install_date,Lon,idDepot,macAddress,versionFirmware,signal_dbm,lat,Vendor,hardware_model,id_unit,Technician,ipv4
gateway_id,,,,,,,,,,,,,
GW-01999,2024/05/14,2016-06-21,-6.24800,43,de:ba:41:f3:c9:99,v2.7.0,-67.0,38.60958,Andrade S.A.,GWX-100,763.0,Jeremy Sherman,218.108.94.86
GW-02000,2024-05-22,2022/06/04,-8.68316,111,c7:76:03:bd:72:03,v2.7.0,-73.5,40.39939,Tavares,NODE-7,NaN,Toralf Mentzel,114.107.184.6
GW-02001,12 Dec 2024,2017/05/29,-8.69767,39,b0:46:b5:c0:ce:69,v1.2.5,-65.2,38.70258,Pacheco,GWX-200,NaN,Prof. Cornelia Bolnbach B.A.,100.208.230.119
GW-02002,2024-11-28,2019/01/30,-7.21550,42,c1:1e:a9:70:b6:c3,v3.4.1,-69.0,39.55325,Speer,NODE-9,NaN,Ivan Leal,15.223.22.198
GW-02003,2025-01-11,"12/08/2019, 00:00:00",-8.99649,48,f7:67:09:c5:d1:e5,v2.7.0,-73.7,39.84780,Amorim,GWX-300,NaN,Elisabeth Seifert,187.35.83.218
GW-02004,2024/08/28,2022/09/22,-8.94349,48,de:79:e5:97:58:d6,v1.2.5,-79.9,39.96341,Koch-Moody,GWX-300,NaN,Isabela Barbosa,55.172.222.1
GW-02005,"08/15/2024, 00:00:00","09/22/2020, 00:00:00",-7.26141,35,59:5f:5a:17:28:4c,v3.4.1,-48.6,39.86669,Amorim,NODE-9,NaN,Matthew Torres,238.10.177.149
GW-02006,2024/11/18,2019/03/14,-8.17182,44,15:5f:d9:70:fe:0a,v2.7.0,-62.3,39.37855,Fritsch,NODE-9,NaN,Stephanie Allison,107.109.53.8
GW-02007,2024-06-13,2016-01-18,-6.65883,52,91:dc:69:36:ac:37,v2.7.0,-67.1,41.08669,Mills LLC,NODE-7,NaN,Larry Roberson,247.41.193.19
GW-02008,2024-05-06,27 Apr 2023,-8.12555,87,2c:04:fe:eb:59:45,v2.7.0,-69.6,40.42062,Speer,GWX-100,NaN,Crystal Mayo,149.165.225.166
GW-02009,12 Jul 2024,2020-03-05,-8.93940,6,7c:12:46:1c:62:14,v1.2.5,-72.7,41.30016,Freeman-Reid,NODE-9,NaN,Slobodan Häring,220.89.19.109
GW-02010,12 Oct 2024,2024-10-06,-6.28238,30,15:42:3e:99:74:fd,v2.7.0,-63.3,40.99563,Barrett Inc,GWX-200,NaN,Miriam Pacheco,19.92.207.53
GW-02011,2024-02-01,07 Oct 2017,-7.71184,116,c0:4a:f1:3c:3b:b8,v3.4.1,-68.0,41.44652,Pinheiro,GWX-100,NaN,Elenore Herrmann,223.218.103.29
GW-02012,2024/07/26,2018/09/29,-6.49690,20,aa:f2:ab:6c:b2:a0,v2.7.0,-70.2,39.54574,Zorbach,GWX-100,NaN,Nuran Klapp,227.22.212.249
GW-02013,26 Jan 2025,23 Oct 2020,-8.60215,65,c5:1d:8b:d3:3e:6d,v2.7.0,-64.4,39.98694,Speer,NODE-7,NaN,Frau Adelinde Birnbaum,221.101.8.92
GW-02014,2024/09/23,2024/01/22,-8.54987,99,e0:02:13:15:8d:fb,v2.7.0,-74.1,41.06513,Pinto S.A.,NODE-7,NaN,Kristy Thompson,206.163.80.62
GW-02015,2024/07/15,2016/12/08,-7.38500,19,18:24:4f:59:f8:e7,v2.7.0,-66.7,39.04825,Amorim,GWX-100,NaN,Sofia Loureiro,96.97.156.99
GW-02016,2024-07-08,12 May 2021,-7.92268,38,15:93:bc:39:6e:31,v2.7.0,-70.0,40.35019,Harrison Inc,GWX-100,NaN,Fábio Branco,51.161.185.131
GW-02017,2024/01/20,11 May 2024,-8.15018,104,7b:e9:2b:e9:e0:b5,v1.2.5,-63.4,39.66639,Bell-Sosa,GWX-200,NaN,John Willis,128.172.202.169
GW-02018,2024-09-28,01 Apr 2017,-7.77767,95,76:13:25:48:49:06,v1.2.5,-65.8,40.25694,Mills LLC,GWX-300,NaN,Simão Nascimento,197.76.132.202
GW-02019,2024-10-13,2019-06-12,-7.23011,39,03:0c:7d:54:b8:53,v3.4.1,-59.1,39.67323,Koch-Moody,GWX-300,NaN,Richard Budig-Flantz,22.173.131.35

gateway_id - Textual - maybe change to numerical(remove GW from start)

seen_last - Time-series

install_date - Time-series

lon - Numerical(continuous)

idDeport - Discrete

macAddress - Textual ? - cant decide same as ip

versionFirmware - Categorical

signal_dbm - Numerical(continuous)

lat - Numerical(continuous)

Vendor - Categorical

hardware_model - Categorical

id_unit - Numerical(continuous) - change to discrete (all nums have .0) / from 2000 to end are NaN - problem? 

Technician - Categorical(nominal)

ipv4 - Textual ? - cant decide

In [11]:
data_2 = pd.read_csv(filename_2, 
                    sep='\t')
data_2.head(20)

,id_unit,cycle_ts,currentMotor,dp_filter,oilTemperature,pressure_reservoir,rmsVibration,Flowmeter,dischargeDewpoint,Failure
0,U00078,24 Sep 2023,2.91072,17.08727,63.17362,10.42780,5.53225,24.90723,5.49963,0
1,U01922,2023-10-05,5.20071,14.68177,36.67755,8.84326,6.40699,26.62476,7.60072,1
2,U00548,2023-10-18,5.56161,44.22325,43.50675,8.03135,4.30464,26.39225,5.25673,0
3,U01551,21 Mar 2023,5.12227,21.50330,63.91073,7.86316,1.66650,22.98348,5.09449,1
4,U00298,04 Oct 2023,5.11036,29.84890,64.71004,9.78952,2.82960,33.75524,11.50507,0
5,U01522,12 Dec 2023,2.47593,NaN,63.34515,8.66470,5.10853,27.65622,5.79981,1
6,U00748,2023/04/23,6.60443,18.84023,40.67046,8.61937,NaN,25.53233,3.43388,1
7,U00565,2023/03/24,6.48482,26.42038,52.23038,8.45314,1.85331,26.09878,7.24156,0
8,U00588,"01/02/2023, 14:07:00",6.63109,NaN,60.44142,9.34893,3.28290,28.68901,16.55528,1
9,U01188,2023-03-17,4.51353,45.42224,57.41512,8.61459,2.45468,33.13947,8.77440,1
10,U01709,09 Nov 2023,3.16319,19.49012,51.10157,7.82277,5.84209,24.56492,11.76392,0
11,U90462,28 Apr 2023,6.81055,19.47220,35.24649,7.68973,1.16562,26.61161,5.74717,0
12,U00777,2023-03-20,8.90192,31.58637,76.53772,9.24322,3.65537,26.53945,6.02036,1
13,U01932,2023/12/15,2.73218,27.11226,61.66585,9.65346,2.54976,29.35800,5.44671,1
14,U00174,27 May 2023,2.85316,15.03347,44.36640,9.64954,1.64047,32.99018,10.54440,0
15,U00615,20 Aug 2023,5.65556,17.85116,44.59741,7.77974,1.67308,30.21856,8.61138,0
16,U01772,10 Oct 2023,3.85656,26.07213,83.24260,8.42842,6.11515,30.74529,8.94967,0
17,U01051,14 Sep 2023,3.46227,11.79231,42.08313,8.16432,7.52198,34.88536,7.52025,0
18,U00891,"03/08/2023, 06:21:00",4.45184,13.87520,40.60342,8.99945,1.88199,26.34662,7.40281,1
19,U01271,2023/02/03,4.41198,16.52390,59.53424,8.11807,9.24010,37.36621,10.06421,0

id_unit - Categorical(nominal) - maybe change to numerical(remove U from start because units table has numerical id)

cycle_ts - Time-series

currentMotor - Numerical(continuous)

dp_filter - Numerical(continuous)

oilTemperature - Numerical(continuous)

presure_reservoir - Numerical(continuous)

rmsVibration - Numerical(continuous)

Flowmeter - Numerical(continuous)
 
dischargeDewpoint - Numerical(continuous)

Failure - Categorical(Boolean)

In [ ]:
data_3 = pd.read_csv(filename_3, 
                    sep=',',index_col=5
                    )
data_3.head(20)

,idDepot,duty_class,year_commission,serviceHours,overhaul_last,serial_number
id_unit,,,,,,
1891,63,2,2021,13920.4,"05/19/2019, 00:00:00",XY-3440-63587
1892,85,H,2019,20134.1,"01/11/2023, 00:00:00",IT-4214-73893
1893,83,heavy,2023,5240.7,2018/11/01,YH-1075-20568
1894,116,heavy,2012,44124.6,17 Sep 2022,JN-9081-07330
1895,2,light,2019,18932.9,"11/08/2022, 00:00:00",XF-9990-83343
1896,14,3,2013,41009.1,2016/12/24,SE-6110-32800
1897,23,med,2024,3094.9,"04/25/2022, 00:00:00",KL-8453-63044
1898,9,1,2020,14352.0,"07/23/2019, 00:00:00",RC-6478-97526
1899,63,3,2023,6083.2,2019/01/12,GJ-4077-99586
1900,78,3,2021,12147.3,"07/19/2018, 00:00:00",BU-0499-99242
1901,5,N,2023,4758.5,2024/12/26,FT-6272-01431
1902,86,3,2021,12752.8,12 Oct 2015,PF-6723-89257
1903,0,L,2020,NaN,2018/08/03,PO-1963-43584
1904,66,2,2022,8053.8,05 Jul 2020,FC-9369-80634
1905,118,H,2022,9304.4,2015/07/01,KI-0434-98492
1906,61,normal,2018,21116.0,29 Dec 2019,EM-7390-69231
1907,30,heavy,2022,8636.7,"09/14/2018, 00:00:00",UE-2421-14577
1908,78,normal,2021,11384.6,2019/11/12,ML-5360-49938
1909,100,N,2019,20839.7,"02/02/2022, 00:00:00",EQ-7820-74315
1910,66,N,2019,18548.8,23 Mar 2020,LJ-0202-44606

id_unit - Numerical

idDeport - Numerical

duty_class - Categorical - change category names (can see diff names for 1 category)

year_commision - Numerical - not sure its ok

service_hours - Numerical(Continuous)

overhaul_last - Time-series

serial_number - Textual

In [25]:
data_1.info()

<class 'pandas.DataFrame'>
Index: 16000 entries, GW-00000 to GW-15999
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   seen_last        16000 non-null  str
 1   install_date     16000 non-null  str
 2   Lon              16000 non-null  float64
 3   idDepot          16000 non-null  int64
 4   macAddress       16000 non-null  str
 5   versionFirmware  16000 non-null  str
 6   signal_dbm       16000 non-null  float64
 7   lat              16000 non-null  float64
 8   Vendor           16000 non-null  str
 9   hardware_model   16000 non-null  str
 10  id_unit          2000 non-null   float64
 11  Technician       16000 non-null  str
 12  ipv4             16000 non-null  str
dtypes: float64(4), int64(1), str(8)
memory usage: 3.3 MB

id_unit from 2000 to end are NaN - problem?

In [26]:
data_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 14052 entries, 0 to 14051
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   id_unit             14052 non-null  str
 1   cycle_ts            14052 non-null  str
 2   currentMotor        14052 non-null  float64
 3   dp_filter           13503 non-null  float64
 4   oilTemperature      14052 non-null  float64
 5   pressure_reservoir  14052 non-null  float64
 6   rmsVibration        13534 non-null  float64
 7   Flowmeter           14052 non-null  float64
 8   dischargeDewpoint   14052 non-null  float64
 9   Failure             14052 non-null  int64
dtypes: float64(7), int64(1), str(2)
memory usage: 1.3 MB

dp_filter and 13534 have NaN values - remove / replace

In [27]:
data_3.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 1 to 2000
Data columns (total 6 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   idDepot          2000 non-null   int64
 1   duty_class       2000 non-null   str
 2   year_commission  2000 non-null   int64
 3   serviceHours     1900 non-null   float64
 4   overhaul_last    2000 non-null   str
 5   serial_number    2000 non-null   str
dtypes: float64(1), int64(2), str(3)
memory usage: 149.5 KB

serviceHours - NaN values remove / replace

In [28]:
data_1.describe(include='all')

,seen_last,install_date,Lon,idDepot,macAddress,versionFirmware,signal_dbm,lat,Vendor,hardware_model,id_unit,Technician,ipv4
count,16000,16000,16000.000000,16000.000000,16000,16000,16000.000000,16000.000000,16000,16000,2000.000000,16000,16000
unique,1600,9723,NaN,NaN,16000,3,NaN,NaN,38,5,NaN,120,16000
top,2024-08-05,2024/06/04,NaN,NaN,e2:f9:05:83:4d:20,v1.2.5,NaN,NaN,Speer,NODE-9,NaN,Miguel Marques,67.49.73.170
freq,22,7,NaN,NaN,1,5359,NaN,NaN,810,3263,NaN,165,1
mean,NaN,NaN,-7.751588,58.854125,NaN,NaN,-70.170300,40.155156,NaN,NaN,1000.500000,NaN,NaN
std,NaN,NaN,0.891284,34.567290,NaN,NaN,10.006577,0.900882,NaN,NaN,577.494589,NaN,NaN
min,NaN,NaN,-9.299980,0.000000,NaN,NaN,-107.300000,38.600070,NaN,NaN,1.000000,NaN,NaN
25%,NaN,NaN,-8.524577,29.000000,NaN,NaN,-77.000000,39.373440,NaN,NaN,500.750000,NaN,NaN
50%,NaN,NaN,-7.758115,59.000000,NaN,NaN,-70.200000,40.163690,NaN,NaN,1000.500000,NaN,NaN
75%,NaN,NaN,-6.980605,89.000000,NaN,NaN,-63.400000,40.937605,NaN,NaN,1500.250000,NaN,NaN
max,NaN,NaN,-6.200070,119.000000,NaN,NaN,-40.000000,41.699910,NaN,NaN,2000.000000,NaN,NaN

In [30]:
data_2.describe(include='all')

,id_unit,cycle_ts,currentMotor,dp_filter,oilTemperature,pressure_reservoir,rmsVibration,Flowmeter,dischargeDewpoint,Failure
count,14052,14052,14052.000000,13503.000000,14052.000000,14052.000000,13534.000000,14052.000000,14052.000000,14052.000000
unique,2112,4579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,U01347,13 Dec 2023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,17,21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,5.277158,24.073502,50.628361,8.698509,3.083622,27.925684,7.971619,0.118844
std,NaN,NaN,2.893927,11.434870,68.623763,0.601964,1.643651,4.007567,3.507052,0.323617
min,NaN,NaN,0.115880,7.081150,-999.000000,6.500000,0.500000,15.000000,-5.117820,0.000000
25%,NaN,NaN,3.731485,16.246110,46.753862,8.298048,1.936292,25.222520,5.666065,0.000000
50%,NaN,NaN,5.127835,21.249320,55.072740,8.696900,2.718050,27.936505,7.972520,0.000000
75%,NaN,NaN,6.643298,28.690820,63.030540,9.102232,3.830090,30.630375,10.308608,0.000000
max,NaN,NaN,99.000000,120.000000,95.000000,10.500000,14.000000,40.000000,23.904830,1.000000

In [31]:
data_3.describe(include='all')

,idDepot,duty_class,year_commission,serviceHours,overhaul_last,serial_number
count,2000.000000,2000,2000.000000,1900.000000,2000,2000
unique,NaN,20,NaN,NaN,1842,2000
top,NaN,L,NaN,NaN,"09/30/2019, 00:00:00",GQ-0521-56531
freq,NaN,252,NaN,NaN,3,1
mean,54.737500,NaN,2020.343000,14588.644842,NaN,NaN
std,34.325074,NaN,2.547076,8953.209427,NaN,NaN
min,0.000000,NaN,2012.000000,1303.000000,NaN,NaN
25%,24.000000,NaN,2019.000000,8224.525000,NaN,NaN
50%,53.000000,NaN,2021.000000,12343.300000,NaN,NaN
75%,83.000000,NaN,2022.000000,18475.050000,NaN,NaN
max,119.000000,NaN,2024.000000,45000.000000,NaN,NaN